version: '3.9'

services:
  mongoDB:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongoDB:/data/db
  content_api:
    build: ./Content_Service
    ports:
      - '5000:5000'
    extra_hosts:
      - "localhost:127.0.0.1"
    volumes:
      - ./Content_Service:/usr/src/app
    environment:
      PORT: 5000
      DB_name: mydb
      DB_URI: mongodb://mongoDB:27017
      HOSTNAME: 0.0.0.0
    depends_on:
      - mongoDB
  
  user_interaction:
    build: ./User_Interaction_Service
    ports:
      - '5001:5001'
    extra_hosts:
      - "localhost:127.0.0.1"
    volumes:
      - ./User_Interaction_Service:/usr/src/app
    environment:
      PORT: 5001
      DB_name: mydb2
      DB_URI: mongodb://mongoDB:27017
      HOSTNAME: 0.0.0.0
    depends_on:
      - mongoDB

  users:
    build: ./User_Service
    ports:
      - '5002:5002'
    extra_hosts:
      - "localhost:127.0.0.1"
    volumes:
      - ./User_Service:/usr/src/app
    environment:
      PORT: 5002
      DB_name: mydb3
      DB_URI: mongodb://mongoDB:27017
      HOSTNAME: 0.0.0.0
    depends_on:
      - mongoDB

volumes:
  mongoDB: {}
